### ISSUE TITLE
'View in your browser' doesn't work

### ISSUE THREAD

**Issue by clarkac1** [veda-consulting-company/uk.co.vedaconsulting.mosaico#78] opened 2016-12-13 20:11 UTC
The 'View in your browser' link doesn't do anything - nothing seems to be generated in it - there is no link.
This is using Firefox 50 and Chrome 55, with CiviCRM 4.6.22

Andy Clark

**Comment by totten** [comment] 2017-02-25 21:15
This should be fixed by #98 (specifically d4d6075bf636efafbb909e3a6a1460d15c228f3b).

**Comment by kngs** [comment] 2017-08-24 15:40
I have two installs whose View in browser works with a URL generated of:
https://mygoodsite.org/civicrm?page=CiviCRM&q=civicrm/mailing/view&reset=1&id=213

but I have another site whose view in browser URL generated yields a blank page and is:
https://www.mybadsite.org/civicrm/?page=CiviCRM&q=civicrm/mailing/view&reset=1&id=447
(note the www and the extra / before ?page=)

The bad site's view in browser URL with the old mailer had this same format (with the www and the extra /) and it works.

Removing the extra / and/or the www does not help :/
I've made both the Resource URLs and Directory paths all absolute but no help :/
Any ideas on why the URLs generated are different or what the problem is?

Thanks! Karen

All sites are:
WP
Civi 4.7.22 or 4.7.23 
Mosaico 2.0-beta3
FlexMailer 0.2-alpha2
Shoreditch 0.1-alpha9

**Comment by kngs** [comment] 2018-03-01 18:55
There appears to be a conflict with Smarty as I've found that disabling Smarty in civicrm.settings.php allows my problem site's View in Browser to work again.

(FYI, the URL still has the same format as mentioned above.)

**Comment by mwestergaard** [comment] 2019-02-18 19:22
@kngs That was my experience, too, with beta3. Currently seems ok to have Smarty enabled with Mosaico 2.0-beta4.1544700816, Shoreditch 0.1-alpha30, andFlexMailer 1.0-beta1.

**Closed** 2021-01-07 18:51 UTC
Labels: topic:hyperlinking
